# Generated by Django 3.2.11 on 2022-02-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rangoFecha', models.CharField(max_length=150)),
                ('posicion', models.CharField(max_length=150)),
                ('empresa', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('EXP', 'Experiencias'), ('EDU', 'Educacion')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('porcentaje', models.IntegerField()),
                ('tipo', models.CharField(choices=[('SFT', 'Habilidad blanda'), ('HRD', 'Habilidad dura'), ('LNG', 'Idioma')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='IdiomaPalabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabraEspanol', models.CharField(max_length=150)),
                ('palabraIngles', models.CharField(max_length=150)),
                ('clave', models.CharField(max_length=20)),
            ],
        ),
    ]
