# Generated by Django 3.2.11 on 2022-05-08 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCortoDefecto', models.CharField(max_length=50)),
                ('nombreLargoDefecto', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=2)),
                ('titulo', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='idiomas')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(blank=True, max_length=50)),
                ('nombreCargo', models.CharField(blank=True, max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('texto', models.TextField(blank=True, null=True)),
                ('imagenPerfil', models.ImageField(upload_to='testimoniales')),
                ('mostrarPagina', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactoAsunto',
            fields=[
                ('idioma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Portfolio.idioma')),
                ('nombreCorto', models.CharField(blank=True, max_length=50)),
                ('nombreLargo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IdiomaEntorno',
            fields=[
                ('idioma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Portfolio.idioma')),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('menuInicio', models.CharField(blank=True, max_length=50)),
                ('menuAcerca', models.CharField(blank=True, max_length=50)),
                ('menuResumen', models.CharField(blank=True, max_length=50)),
                ('menuPortafolio', models.CharField(blank=True, max_length=50)),
                ('menuBlog', models.CharField(blank=True, max_length=50)),
                ('menuContacto', models.CharField(blank=True, max_length=50)),
                ('inicioPrefijoSoy', models.CharField(blank=True, max_length=50)),
                ('acercaPresentacion', models.CharField(blank=True, max_length=50)),
                ('acercaCumpleanos', models.CharField(blank=True, max_length=50)),
                ('acercaTelefono', models.CharField(blank=True, max_length=50)),
                ('acercaCorreo', models.CharField(blank=True, max_length=50)),
                ('acercaDireccion', models.CharField(blank=True, max_length=50)),
                ('resumenEducacion', models.CharField(blank=True, max_length=50)),
                ('resumenExperiencia', models.CharField(blank=True, max_length=50)),
                ('resumenHabilidades', models.CharField(blank=True, max_length=50)),
                ('resumenHabilidadesBlandas', models.CharField(blank=True, max_length=50)),
                ('resumenHabilidadesIdiomas', models.CharField(blank=True, max_length=50)),
                ('resumenPremios', models.CharField(blank=True, max_length=50)),
                ('resumenBotonCv', models.CharField(blank=True, max_length=50)),
                ('resumenBotonContratarme', models.CharField(blank=True, max_length=50)),
                ('portafolioMisTrabajos', models.CharField(blank=True, max_length=50)),
                ('portafolioPrecios', models.CharField(blank=True, max_length=50)),
                ('portafolioTestimonios', models.CharField(blank=True, max_length=50)),
                ('portafolioClientes', models.CharField(blank=True, max_length=50)),
                ('portafolioPreciosDetalles', models.CharField(blank=True, max_length=50)),
                ('contactoTitulo', models.CharField(blank=True, max_length=50)),
                ('contactoSubitulo', models.CharField(blank=True, max_length=50)),
                ('contactoCorreoEtiqueta', models.CharField(blank=True, max_length=50)),
                ('contactoCorreoGuia', models.CharField(blank=True, max_length=50)),
                ('contactoTelefonoEtiqueta', models.CharField(blank=True, max_length=50)),
                ('contactoTelefonoGuia', models.CharField(blank=True, max_length=50)),
                ('contactoAsuntoEtiqueta', models.CharField(blank=True, max_length=50)),
                ('contactoMensajeEtiqueta', models.CharField(blank=True, max_length=50)),
                ('contactoMensajeGuia', models.CharField(blank=True, max_length=50)),
                ('contactoBotonEtiqueta', models.CharField(blank=True, max_length=50)),
                ('blogUltimasNoticias', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Entorno por idioma',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idioma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Portfolio.idioma')),
                ('nombreCorto', models.CharField(blank=True, max_length=50)),
                ('nombreLargo', models.CharField(blank=True, max_length=100)),
                ('enlacePresentacion', models.CharField(blank=True, max_length=100)),
                ('imagenPerfil', models.ImageField(upload_to='perfiles')),
                ('soyLista', models.CharField(blank=True, max_length=200)),
                ('saludo', models.CharField(blank=True, max_length=50)),
                ('descipcion', models.TextField(blank=True, null=True)),
                ('enlaceLinkedin', models.CharField(blank=True, max_length=100)),
                ('enlaceGithub', models.CharField(blank=True, max_length=100)),
                ('enlaceTwitter', models.CharField(blank=True, max_length=100)),
                ('cumpleanos', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('correo', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('archivoCv', models.FileField(upload_to='cvs')),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='PerfilServicios',
            fields=[
                ('idioma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Portfolio.idioma')),
                ('servicio1Texto', models.CharField(blank=True, max_length=50)),
                ('servicio1Url', models.CharField(blank=True, max_length=100)),
                ('servicio2Texto', models.CharField(blank=True, max_length=50)),
                ('servicio2Url', models.CharField(blank=True, max_length=100)),
                ('servicio3Texto', models.CharField(blank=True, max_length=50)),
                ('servicio3Url', models.CharField(blank=True, max_length=100)),
                ('servicio4Texto', models.CharField(blank=True, max_length=50)),
                ('servicio4Url', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Servicios por perfil',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCorto', models.CharField(blank=True, max_length=50)),
                ('nombreLargo', models.CharField(blank=True, max_length=100)),
                ('imagenProyecto', models.ImageField(upload_to='proyectos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('porcentaje', models.IntegerField()),
                ('tipo', models.CharField(choices=[('SFT', 'Habilidad blanda'), ('HRD', 'Habilidad dura'), ('LNG', 'Idioma')], max_length=3)),
                ('idioma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Portfolio.idioma')),
            ],
            options={
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rangoFecha', models.CharField(max_length=150)),
                ('posicion', models.CharField(max_length=150)),
                ('empresa', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('EXP', 'Experiencias'), ('EDU', 'Educacion'), ('PRE', 'Premio')], max_length=3)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.idioma')),
            ],
            options={
                'verbose_name_plural': 'Formaciones',
            },
        ),
        migrations.CreateModel(
            name='CategoriaIdioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCorto', models.CharField(max_length=50)),
                ('nombreLargo', models.CharField(blank=True, max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.categoria')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.idioma')),
            ],
        ),
    ]
