# Generated by Django 3.2.11 on 2022-03-03 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=2)),
                ('titulo', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='idiomas')),
            ],
        ),
        migrations.DeleteModel(
            name='IdiomaPalabra',
        ),
        migrations.CreateModel(
            name='IdiomaEntorno',
            fields=[
                ('idioma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Portfolio.idioma')),
                ('titulo', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
