# Generated by Django 3.2.11 on 2022-03-06 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_auto_20220303_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacion',
            name='idioma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Portfolio.idioma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habilidad',
            name='idioma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Portfolio.idioma'),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='acercaCorreo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='acercaCumpleanos',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='acercaTelefono',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='menuAcerca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='menuBlog',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='menuContacto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='menuInicio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='menuPortafolio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='menuResumen',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='resumenEducacion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='resumenExperiencia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='resumenHabilidades',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='resumenPremios',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
