# Generated by Django 3.2.11 on 2022-03-06 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_auto_20220305_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoAsunto',
            fields=[
                ('idioma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Portfolio.idioma')),
                ('nombreCorto', models.CharField(blank=True, max_length=50)),
                ('nombreLargo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idioma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Portfolio.idioma')),
                ('nombreCorto', models.CharField(blank=True, max_length=50)),
                ('nombreLargo', models.CharField(blank=True, max_length=100)),
                ('enlacePresentacion', models.CharField(blank=True, max_length=100)),
                ('imagenPerfil', models.ImageField(upload_to='perfiles')),
                ('soyLista', models.CharField(blank=True, max_length=200)),
                ('saludo', models.CharField(blank=True, max_length=50)),
                ('descipcion', models.CharField(blank=True, max_length=50)),
                ('enlaceLinkedin', models.CharField(blank=True, max_length=100)),
                ('enlaceGithub', models.CharField(blank=True, max_length=100)),
                ('enlaceTwitter', models.CharField(blank=True, max_length=100)),
                ('archivoCv', models.FileField(upload_to='cvs')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilServicios',
            fields=[
                ('idioma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Portfolio.idioma')),
                ('servicio1Texto', models.CharField(blank=True, max_length=50)),
                ('servicio1Url', models.CharField(blank=True, max_length=100)),
                ('servicio2Texto', models.CharField(blank=True, max_length=50)),
                ('servicio2Url', models.CharField(blank=True, max_length=100)),
                ('servicio3Texto', models.CharField(blank=True, max_length=50)),
                ('servicio3Url', models.CharField(blank=True, max_length=100)),
                ('servicio4Texto', models.CharField(blank=True, max_length=50)),
                ('servicio4Url', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='contactoAsuntoEtiqueta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='contactoBotonEtiqueta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='contactoCorreoEtiqueta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='contactoCorreoGuia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='contactoMensajeEtiqueta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='contactoMensajeGuia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='contactoSubitulo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='contactoTelefonoEtiqueta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='contactoTelefonoGuia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='contactoTitulo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idiomaentorno',
            name='inicioPrefijoSoy',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
