# Generated by Django 3.2.11 on 2022-05-02 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0006_auto_20220307_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCorto', models.CharField(max_length=50)),
                ('nombreLargo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='formacion',
            name='tipo',
            field=models.CharField(choices=[('EXP', 'Experiencias'), ('EDU', 'Educacion'), ('PRE', 'Premio')], max_length=3),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCorto', models.CharField(blank=True, max_length=50)),
                ('nombreLargo', models.CharField(blank=True, max_length=100)),
                ('imagenProyecto', models.ImageField(upload_to='proyectos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.categoria')),
            ],
        ),
    ]
