# Generated by Django 3.2.11 on 2022-05-04 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0008_auto_20220503_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIdioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCorto', models.CharField(max_length=50)),
                ('nombreLargo', models.CharField(blank=True, max_length=100)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.idioma')),
            ],
        ),
    ]
